export const copy = {
  en: {
    skip: "Skip to content",
    nav: {
      experience: "Explore services",
      language: "Haitian Creole support",
      providers: "For service providers",
      about: "About",
      menu: "Menu",
      close: "Close",
    },
    hero: {
      eyebrow: "Services for the Haitian community",
      title: "Find the service you need and know who can help in Haitian Creole.",
      creoleLine: "Find the services you need, in your language.",
      body: "Search for doctors, lawyers, housing help, tax services, local businesses, and more. Before you call, KONEKT shows whether the provider, a staff member, or an interpreter can help you in Haitian Creole.",
      primary: "Find a service",
      secondary: "Add or manage a service",
      preview: "Search live providers",
    },
    trust: {
      title: "Get the information you need before you call.",
      body: "You do not need an account to search. Compare services, locations, hours, and Haitian Creole support, then contact the provider directly.",
      items: ["No account needed", "English and Haitian Creole", "Clear language support", "Provider documents stay private"],
    },
    access: {
      eyebrow: "Haitian Creole support",
      title: "Know who will speak Haitian Creole with you.",
      body: "KONEKT tells you whether the provider speaks Haitian Creole, a staff member can help, or an interpreter is available.",
      modes: [
        { icon: "translate", title: "The provider speaks Haitian Creole", text: "You can receive the service directly in Haitian Creole." },
        { icon: "buildings", title: "A staff member speaks Haitian Creole", text: "Someone on the provider's team can help you in Haitian Creole." },
        { icon: "phone-call", title: "An interpreter is available", text: "The provider can arrange an interpreter when you need one." },
      ],
    },
    services: {
      eyebrow: "What do you need?",
      title: "Search by the kind of help you need.",
      body: "Each profile shows details that fit the service, such as insurance for healthcare, appointment links, business hours, and contact information.",
      explore: "Search providers",
      categories: [
        { icon: "first-aid", title: "Healthcare", text: "Clinics, doctors, mental health, pharmacies, and insurance details." },
        { icon: "scales", title: "Legal & Immigration", text: "Immigration, family law, estates, and practical legal support." },
        { icon: "calculator", title: "Tax & Financial", text: "Tax preparation, bookkeeping, credit, and financial guidance." },
        { icon: "house", title: "Real Estate & Housing", text: "Housing services, rentals, home support, and real estate." },
        { icon: "cooking-pot", title: "Food & Community", text: "Restaurants, food support, and community organizations." },
        { icon: "storefront", title: "Local Services", text: "Beauty, translation, professional services, and community businesses." },
      ],
    },
    provider: {
      eyebrow: "For providers",
      title: "Help people find and understand your service.",
      body: "If your service is already listed, request permission to manage it. If it is not listed, add a new profile with your contact details, hours, services, and Haitian Creole support.",
      primary: "Open provider account",
      secondary: "Learn how KONEKT reviews profiles",
      note: "People can see your public profile. Only authorized reviewers can see your verification documents.",
    },
    close: {
      eyebrow: "KONEKT for iPhone and Android",
      title: "Find the right place to call before you make the call.",
      body: "Search published providers now. Official App Store and Google Play links will appear here when the apps are publicly available.",
      primary: "Search providers",
      secondary: "Get support",
    },
  },
  ht: {
    skip: "Ale dirèk nan kontni an",
    nav: {
      experience: "Chèche sèvis",
      language: "Èd an Kreyòl",
      providers: "Pou founisè",
      about: "Konsènan nou",
      menu: "Meni",
      close: "Fèmen",
    },
    hero: {
      eyebrow: "Jwenn sèvis pou kominote ayisyen an",
      title: "Jwenn sèvis ou bezwen an epi konnen kiyès ki ka ede w an Kreyòl.",
      creoleLine: "Jwenn sèvis ou bezwen yo, nan lang ou.",
      body: "Chèche doktè, avoka, èd pou kay, sèvis taks, biznis nan kominote a, ak plis ankò. Anvan ou rele, KONEKT montre si founisè a, yon anplwaye, oswa yon entèprèt ka ede w an Kreyòl.",
      primary: "Chèche sèvis",
      secondary: "Ajoute oswa jere yon sèvis",
      preview: "Chèche founisè ki disponib",
    },
    trust: {
      title: "Jwenn enfòmasyon ou bezwen yo anvan ou rele.",
      body: "Ou pa bezwen kont pou chèche. Konpare sèvis, kote, lè, ak èd an Kreyòl, epi kontakte founisè a dirèkteman.",
      items: ["Pa bezwen kont", "Anglè ak Kreyòl", "Èd an Kreyòl byen esplike", "Dokiman founisè yo rete prive"],
    },
    access: {
      eyebrow: "Èd an Kreyòl",
      title: "Konnen kiyès ki pral pale Kreyòl avè w.",
      body: "KONEKT montre si founisè a pale Kreyòl, si gen yon anplwaye ki ka ede w, oswa si gen yon entèprèt.",
      modes: [
        { icon: "translate", title: "Founisè a pale Kreyòl", text: "Ou ka resevwa sèvis la dirèkteman an Kreyòl." },
        { icon: "buildings", title: "Yon anplwaye pale Kreyòl", text: "Yon moun nan ekip la ka ede w an Kreyòl." },
        { icon: "phone-call", title: "Gen yon entèprèt", text: "Founisè a ka jwenn yon entèprèt lè ou bezwen youn." },
      ],
    },
    services: {
      eyebrow: "Ki sa ou bezwen?",
      title: "Chèche selon kalite èd ou bezwen an.",
      body: "Chak pwofil montre enfòmasyon ki mache ak sèvis la, tankou asirans pou swen sante, lyen randevou, lè biznis, ak kontak.",
      explore: "Chèche founisè",
      categories: [
        { icon: "first-aid", title: "Swen sante", text: "Klinik, doktè, sante mantal, famasi, ak enfòmasyon sou asirans." },
        { icon: "scales", title: "Lalwa ak Imigrasyon", text: "Imigrasyon, dwa fanmi, byen ak testaman, ak sipò legal." },
        { icon: "calculator", title: "Taks ak Finans", text: "Preparasyon taks, kontablite, kredi, ak konsèy finansye." },
        { icon: "house", title: "Kay ak Imobilye", text: "Lwaye, sèvis pou kay, sipò lojman, ak imobilye." },
        { icon: "cooking-pot", title: "Manje ak Kominote", text: "Restoran, sipò alimantè, ak òganizasyon kominotè." },
        { icon: "storefront", title: "Sèvis Lokal", text: "Bote, tradiksyon, sèvis pwofesyonèl, ak biznis kominotè." },
      ],
    },
    provider: {
      eyebrow: "Pou founisè",
      title: "Ede moun jwenn sèvis ou epi konprann sa ou ofri.",
      body: "Si sèvis ou deja nan lis la, mande pèmisyon pou jere pwofil la. Si li poko nan lis la, ajoute yon pwofil ak kontak, lè, sèvis, ak fason moun ka jwenn èd an Kreyòl.",
      primary: "Louvri kont founisè a",
      secondary: "Kijan KONEKT tcheke pwofil yo",
      note: "Tout moun ka wè pwofil piblik la. Se sèlman moun otorize ki ka wè dokiman verifikasyon yo.",
    },
    close: {
      eyebrow: "KONEKT pou iPhone ak Android",
      title: "Konnen ki kote pou rele anvan ou fè apèl la.",
      body: "Chèche founisè ki pibliye kounye a. Lyen ofisyèl App Store ak Google Play ap parèt isit la lè aplikasyon yo disponib pou tout moun.",
      primary: "Chèche founisè",
      secondary: "Jwenn sipò",
    },
  },
}
