export const copy = {
  en: {
    skip: "Skip to content",
    nav: {
      experience: "Explore services",
      language: "Language access",
      providers: "For providers",
      about: "About",
      menu: "Menu",
      close: "Close",
    },
    hero: {
      eyebrow: "Haitian community service discovery",
      title: "Find the right help. Know how Kreyòl is available.",
      creoleLine: "Jwenn sèvis ou bezwen yo, nan lang ou.",
      body: "KONEKT helps Haitian and Haitian Creole-speaking communities understand who offers the service they need, where to find it, and how language support works before they call.",
      primary: "Explore services",
      secondary: "For providers",
      preview: "Product preview",
    },
    trust: {
      title: "A clearer path to community services.",
      body: "Browse without creating an account. Compare practical details. Contact providers directly when you are ready.",
      items: ["Account-free discovery", "English and Kreyòl", "Clear language access", "Private verification files"],
    },
    access: {
      eyebrow: "Language access",
      title: "Kreyòl access, made clear.",
      body: "A single badge is not enough. KONEKT shows how Kreyòl is available so families can choose with confidence.",
      modes: [
        { icon: "translate", title: "Directly in Kreyòl", text: "The provider can deliver the service in Kreyòl." },
        { icon: "buildings", title: "Through Kreyòl-speaking staff", text: "Someone on the provider's team can support you in Kreyòl." },
        { icon: "phone-call", title: "Through an interpreter", text: "Interpretation can be arranged when direct support is unavailable." },
      ],
    },
    services: {
      eyebrow: "Services that matter",
      title: "Start with what you need.",
      body: "KONEKT keeps healthcare-specific details where they belong and gives every service category the information people need to act.",
      explore: "Open the service preview",
      categories: [
        { icon: "first-aid", title: "Healthcare", text: "Clinics, doctors, mental health, pharmacies, and insurance details." },
        { icon: "scales", title: "Legal & Immigration", text: "Immigration, family law, estates, and practical legal support." },
        { icon: "calculator", title: "Tax & Financial", text: "Tax preparation, bookkeeping, credit, and financial guidance." },
        { icon: "house", title: "Real Estate & Housing", text: "Housing services, rentals, home support, and real estate." },
        { icon: "cooking-pot", title: "Food & Community", text: "Restaurants, food support, and community organizations." },
        { icon: "storefront", title: "Local Services", text: "Beauty, translation, professional services, and community businesses." },
      ],
    },
    provider: {
      eyebrow: "For providers",
      title: "Make your service easier to find and understand.",
      body: "Claim an existing profile or add a new service. Share accurate contact details, hours, service information, and the way your team provides Kreyòl access.",
      primary: "See the provider path",
      secondary: "How review works",
      note: "Public profiles and private verification documents stay separate.",
    },
    close: {
      eyebrow: "KONEKT for iPhone and Android",
      title: "Community discovery should begin with clarity.",
      body: "Explore the product experience today. Store links will appear here only after the official releases are available.",
      primary: "Explore the experience",
      secondary: "Get support",
    },
  },
  ht: {
    skip: "Ale dirèk nan kontni an",
    nav: {
      experience: "Chèche sèvis",
      language: "Aksè nan lang",
      providers: "Pou founisè",
      about: "Konsènan nou",
      menu: "Meni",
      close: "Fèmen",
    },
    hero: {
      eyebrow: "Jwenn sèvis pou kominote ayisyen an",
      title: "Jwenn bon sèvis la. Konnen kijan Kreyòl disponib.",
      creoleLine: "Jwenn sèvis ou bezwen yo, nan lang ou.",
      body: "KONEKT ede kominote ayisyen ak moun ki pale Kreyòl yo konnen kiyès ki bay sèvis yo bezwen an, ki kote pou jwenn li, ak kijan sipò nan lang lan mache anvan yo rele.",
      primary: "Chèche sèvis",
      secondary: "Pou founisè",
      preview: "Apèsi sou pwodwi a",
    },
    trust: {
      title: "Yon chemen ki pi klè pou jwenn sèvis.",
      body: "Gade sèvis yo san ou pa kreye kont. Konpare enfòmasyon ki itil. Kontakte founisè yo dirèkteman lè ou pare.",
      items: ["Pa bezwen kont", "Anglè ak Kreyòl", "Aksè nan lang lan klè", "Dokiman verifikasyon rete prive"],
    },
    access: {
      eyebrow: "Aksè nan lang",
      title: "Konnen kijan Kreyòl disponib.",
      body: "Yon sèl etikèt pa sifi. KONEKT montre kijan sèvis an Kreyòl la disponib pou fanmi yo ka chwazi ak konfyans.",
      modes: [
        { icon: "translate", title: "Dirèkteman an Kreyòl", text: "Founisè a ka bay sèvis la an Kreyòl." },
        { icon: "buildings", title: "Avèk anplwaye ki pale Kreyòl", text: "Yon moun nan ekip la ka ede w an Kreyòl." },
        { icon: "phone-call", title: "Avèk yon entèprèt", text: "Yo ka òganize entèpretasyon lè sipò dirèk pa disponib." },
      ],
    },
    services: {
      eyebrow: "Sèvis ki enpòtan",
      title: "Kòmanse ak sa ou bezwen an.",
      body: "KONEKT mete enfòmasyon medikal yo kote yo dwe ye epi bay chak kategori detay moun bezwen pou yo aji.",
      explore: "Gade apèsi sèvis yo",
      categories: [
        { icon: "first-aid", title: "Swen sante", text: "Klinik, doktè, sante mantal, famasi, ak enfòmasyon sou asirans." },
        { icon: "scales", title: "Lalwa ak Imigrasyon", text: "Imigrasyon, dwa fanmi, byen ak testaman, ak sipò legal." },
        { icon: "calculator", title: "Taks ak Finans", text: "Preparasyon taks, kontablite, kredi, ak konsèy finansye." },
        { icon: "house", title: "Kay ak Imobilye", text: "Lwaye, sèvis pou kay, sipò lojman, ak imobilye." },
        { icon: "cooking-pot", title: "Manje ak Kominote", text: "Restoran, sipò alimantè, ak òganizasyon kominotè." },
        { icon: "storefront", title: "Sèvis Lokal", text: "Bote, tradiksyon, sèvis pwofesyonèl, ak biznis kominotè." },
      ],
    },
    provider: {
      eyebrow: "Pou founisè",
      title: "Fè sèvis ou pi fasil pou moun jwenn ak konprann.",
      body: "Reklame yon pwofil ki deja egziste oswa ajoute yon nouvo sèvis. Bay bon enfòmasyon kontak, lè, sèvis, ak fason ekip ou bay sipò an Kreyòl.",
      primary: "Gade chemen founisè a",
      secondary: "Kijan revizyon mache",
      note: "Pwofil piblik ak dokiman verifikasyon prive rete separe.",
    },
    close: {
      eyebrow: "KONEKT pou iPhone ak Android",
      title: "Jwenn sèvis nan kominote a dwe kòmanse ak bon enfòmasyon.",
      body: "Gade eksperyans pwodwi a jodi a. Lyen magazen yo ap parèt la sèlman lè vèsyon ofisyèl yo disponib.",
      primary: "Gade eksperyans lan",
      secondary: "Jwenn sipò",
    },
  },
}
